/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarjeta;

import cajeroautomaticodian.Conexion;
import cajeroautomaticodian.Principal;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author bboyd
 */
public class Tarjeta extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    public Tarjeta(Principal formulario) {
        initComponents();
        inicarComponentes();
        initBaseDatos();

        this.formulario = formulario;
    }

    public void inicarComponentes() {
        this.setSize(500, 350);
        this.setLocationRelativeTo(null);

    }

    public void validarTarjeta() {

        this.setVisible(false);
    }

    private void initBaseDatos() {
        Connection conexion = Conexion.mySQL("cajero", "root", "");
    }
//comprueba si la cuenta existe y esta activa

    public void consultarCuenta() {
        Connection conexion = null;
        conexion = Conexion.mySQL("cajero", "root", "");
        if (conexion != null) {
            
//Paso 2: Ejecutar una consulta
            try {
                ResultSet rs = null;
                Statement sentencia = conexion.createStatement();
                int nCuenta = Integer.parseInt(txfNumCuenta.getText());
                String sql = "SELECT num_cuenta FROM cuenta where num_cuenta='" + nCuenta + "'";
                rs = sentencia.executeQuery(sql);

//Paso 3: Extrayendo los datos del resultset
                while (rs.next()) {
                    //Recuperar datos por el nombre de la columna
//String clave = rs.getString("clave");
                    ncuenta = rs.getInt("num_cuenta");

                    //Ver valores
                    //System.out.println(clave + ", " + saldo);
                    //System.out.println(saldo);
                    System.out.println("cuenta encontrada");
                    System.out.println(ncuenta);
                    nIntentos = 0;

                }

                if (ncuenta == 0) {
                    System.out.println("esta vacio");
                    System.out.println("cuenta no encontrada");
                    nIntentos++;
                    JOptionPane.showMessageDialog(this, "Tarjeta no valida.");
                    txfNumCuenta.setText("");
                    System.out.println(nIntentos);
                } else {// Al encontrar la cuenta se cierra la ventana, guarda el num_cuenta y habilita la ventana principal
                    validarTarjeta();
                    formulario.setEnabled(true);
                    formulario.setAlwaysOnTop(true);
                    formulario.cuentaValida = ncuenta; // guarda la num_cuenta valida en la variable publica del formulario principal
                }
            } catch (SQLException ex) {
                System.out.println("Error");
            } catch (java.lang.NumberFormatException ex) {
                txfNumCuenta.setText("ERROR");
            }
            {
            }
        }
    }

    //* Cerrando base de datos
    public void cerrarBD(java.awt.event.WindowEvent evt) {
        try {
            System.out.println("Cerrando la base de datos...");
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNumCuenta = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        txfNumCuenta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txfNumCuenta.setText("00000");
        txfNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumCuentaActionPerformed(evt);
            }
        });
        txfNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfNumCuentaKeyPressed(evt);
            }
        });
        getContentPane().add(txfNumCuenta);
        txfNumCuenta.setBounds(90, 160, 210, 30);

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setForeground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setText("aceptar");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(130, 220, 105, 23);

        lblFondo.setBackground(new java.awt.Color(255, 255, 204));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjeta/creditcard.png"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-20, 50, 420, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//evento tecla pulsada
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void txfNumCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNumCuentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumCuentaKeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (nIntentos < 4 && txfNumCuenta.getText() != null) {
            consultarCuenta();
        } else {//Intento de fraude, el cajero se bloquea.
            lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjeta/creditcard-Falsa.png")));
            txfNumCuenta.setText("TARJETA DESTRUIDA");
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txfNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumCuentaActionPerformed

    }//GEN-LAST:event_txfNumCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txfNumCuenta;
    // End of variables declaration//GEN-END:variables
    private Principal formulario;
    private int ncuenta = 0;
    private Connection conexion;
    private Statement sentencia;
    private ResultSet resultado;

    private boolean esValida = false;
    private int nIntentos = 0;
    private boolean bloqueada = true;

}
