/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import usuario.*;
import cajeroautomaticodian.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author bboyd
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Admin(Principal principal) {
        initComponents();
        ventanas();
        this.principal = principal;
        initBaseDatos();
        this.setTitle("Adminin");

    }

    //Pone el tamaño y la posicion cuando se abre un frame o gana focus
    private void framePosicion(JFrame jframe) {
        jframe.setSize(500, 400);//tamaño del jFrame
        jframe.setLocationRelativeTo(null); //jframe al centro
        this.setEnabled(false);
    }

    //Cuando cierro un jframe el frame de admin se vuelve a poner enabled
    private void frameCerrar() {
        this.setEnabled(true);
    }
    private Tarjeta tarjetaClase = new Tarjeta(this);

    private void goTarjeta() {
        tarjetaClase.setVisible(true);
        this.setVisible(false);
        ;
    }

    private void ventanas() {
        this.setSize(807, 740);//tamaño del jFrame
        this.setLocationRelativeTo(null); //jframe al centro
        pnlCajero.setVisible(false);
    }

    //* Cerrando base de datos
    private void initBaseDatos() {
        conexion = Conexion.mySQL("cajero", "root", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionOperacionCajero = new javax.swing.ButtonGroup();
        jFAñadirCuenta = new javax.swing.JFrame();
        btnCuentaAñadir = new javax.swing.JButton();
        txfCuentaAñadir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCuentaAñadir = new javax.swing.JLabel();
        jFBorrarCuenta = new javax.swing.JFrame();
        btnCuentaBorrar = new javax.swing.JButton();
        txfCuentaBorrar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblCuentaBorrar = new javax.swing.JLabel();
        jFModificarCuenta = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        txfApes1 = new javax.swing.JTextField();
        btnMostrarDatos = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txfCuentaModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txfRespuestaModificarCuenta = new javax.swing.JLabel();
        jFTarjetas = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        txfPinAñadir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txfCuentaTarjeta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txfRespuestaTarjeta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        pnlCajero = new javax.swing.JPanel();
        lblCajeroInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptarCajero = new javax.swing.JButton();
        lblCajeroRespuesta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbCajeroRetira = new javax.swing.JRadioButton();
        rbCajeroIngresa = new javax.swing.JRadioButton();
        txfCajero = new javax.swing.JTextField();
        btnCerrarCajero = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblFondoPng = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jFAñadirCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFAñadirCuentaFocusGained(evt);
            }
        });
        jFAñadirCuenta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFAñadirCuentaWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFAñadirCuentaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFAñadirCuentaWindowOpened(evt);
            }
        });
        jFAñadirCuenta.getContentPane().setLayout(null);

        btnCuentaAñadir.setText("Añadir");
        btnCuentaAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaAñadirActionPerformed(evt);
            }
        });
        jFAñadirCuenta.getContentPane().add(btnCuentaAñadir);
        btnCuentaAñadir.setBounds(100, 160, 190, 23);
        jFAñadirCuenta.getContentPane().add(txfCuentaAñadir);
        txfCuentaAñadir.setBounds(100, 130, 190, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUMERO DE LA CUENTA");
        jFAñadirCuenta.getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 190, 20);

        lblCuentaAñadir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCuentaAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFAñadirCuenta.getContentPane().add(lblCuentaAñadir);
        lblCuentaAñadir.setBounds(0, 180, 400, 30);

        jFBorrarCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFBorrarCuentaFocusGained(evt);
            }
        });
        jFBorrarCuenta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFBorrarCuentaWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFBorrarCuentaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFBorrarCuentaWindowOpened(evt);
            }
        });
        jFBorrarCuenta.getContentPane().setLayout(null);

        btnCuentaBorrar.setText("BORRAR");
        btnCuentaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaBorrarActionPerformed(evt);
            }
        });
        jFBorrarCuenta.getContentPane().add(btnCuentaBorrar);
        btnCuentaBorrar.setBounds(100, 160, 190, 23);
        jFBorrarCuenta.getContentPane().add(txfCuentaBorrar);
        txfCuentaBorrar.setBounds(100, 130, 190, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NUMERO DE LA CUENTA");
        jFBorrarCuenta.getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 110, 190, 20);

        lblCuentaBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCuentaBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFBorrarCuenta.getContentPane().add(lblCuentaBorrar);
        lblCuentaBorrar.setBounds(0, 180, 400, 30);

        jFModificarCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFModificarCuentaFocusGained(evt);
            }
        });
        jFModificarCuenta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFModificarCuentaWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFModificarCuentaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFModificarCuentaWindowOpened(evt);
            }
        });
        jFModificarCuenta.getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel6.setText("BUSCAR CUENTA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 40, 130, 30);

        jLabel7.setText("APELLIDOS:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 160, 90, 30);
        jPanel2.add(txfNombre);
        txfNombre.setBounds(140, 110, 180, 30);
        jPanel2.add(txfApes1);
        txfApes1.setBounds(140, 160, 180, 30);

        btnMostrarDatos.setText("MOSTRAR DATOS");
        btnMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrarDatos);
        btnMostrarDatos.setBounds(140, 80, 180, 23);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar);
        btnModificar.setBounds(260, 250, 90, 23);

        txfCuentaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCuentaModificarActionPerformed(evt);
            }
        });
        jPanel2.add(txfCuentaModificar);
        txfCuentaModificar.setBounds(140, 40, 180, 30);

        jLabel10.setText("NOMBRE TITULAR:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 110, 130, 30);

        txfRespuestaModificarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txfRespuestaModificarCuenta);
        txfRespuestaModificarCuenta.setBounds(0, 200, 390, 40);

        jFModificarCuenta.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 300);

        jPanel3.setLayout(null);
        jPanel3.add(txfPinAñadir);
        txfPinAñadir.setBounds(130, 100, 140, 30);

        jLabel9.setText("CUENTA:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 60, 80, 30);

        jLabel11.setText("CODIGO PIN:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 100, 80, 30);

        jButton1.setText("COMPROBAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(290, 60, 100, 30);

        txfCuentaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCuentaTarjetaActionPerformed(evt);
            }
        });
        jPanel3.add(txfCuentaTarjeta);
        txfCuentaTarjeta.setBounds(130, 60, 140, 30);

        jButton2.setText("AÑADIR");
        jPanel3.add(jButton2);
        jButton2.setBounds(130, 140, 140, 23);
        jPanel3.add(txfRespuestaTarjeta);
        txfRespuestaTarjeta.setBounds(0, 200, 400, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AÑADIR CUENTA");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(130, 20, 140, 30);

        jFTarjetas.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu5.setText("AÑADIR / BORRAR");

        jMenuItem8.setText("AÑADIR");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("BORRAR");
        jMenu5.add(jMenuItem9);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("MODIFICAR");

        jMenuItem10.setText("jMenuItem10");
        jMenu7.add(jMenuItem10);

        jMenuBar2.add(jMenu7);

        jFTarjetas.setJMenuBar(jMenuBar2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlCajero.setBackground(new java.awt.Color(51, 51, 255));
        pnlCajero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlCajero.setPreferredSize(new java.awt.Dimension(500, 157));
        pnlCajero.setLayout(null);

        lblCajeroInfo.setBackground(new java.awt.Color(255, 255, 102));
        lblCajeroInfo.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        lblCajeroInfo.setForeground(new java.awt.Color(255, 255, 204));
        lblCajeroInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCajeroInfo.setText("SELECCIONA UNA OPERACION Y CANTIDAD");
        pnlCajero.add(lblCajeroInfo);
        lblCajeroInfo.setBounds(90, 130, 320, 19);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Administracion del Cajero Automatico");
        pnlCajero.add(jLabel2);
        jLabel2.setBounds(40, 30, 450, 29);

        btnAceptarCajero.setText("Aceptar");
        btnAceptarCajero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAceptarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCajeroActionPerformed(evt);
            }
        });
        pnlCajero.add(btnAceptarCajero);
        btnAceptarCajero.setBounds(90, 180, 320, 30);

        lblCajeroRespuesta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCajeroRespuesta.setForeground(new java.awt.Color(255, 255, 204));
        lblCajeroRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCajeroRespuesta.setText("RESPUESTA");
        pnlCajero.add(lblCajeroRespuesta);
        lblCajeroRespuesta.setBounds(90, 210, 320, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("€");
        pnlCajero.add(jLabel3);
        jLabel3.setBounds(410, 160, 34, 26);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        seleccionOperacionCajero.add(rbCajeroRetira);
        rbCajeroRetira.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbCajeroRetira.setForeground(new java.awt.Color(255, 0, 0));
        rbCajeroRetira.setText("Retira");
        jPanel1.add(rbCajeroRetira);

        seleccionOperacionCajero.add(rbCajeroIngresa);
        rbCajeroIngresa.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbCajeroIngresa.setForeground(new java.awt.Color(51, 255, 51));
        rbCajeroIngresa.setText("Ingresa");
        jPanel1.add(rbCajeroIngresa);

        txfCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCajeroActionPerformed(evt);
            }
        });
        jPanel1.add(txfCajero);

        pnlCajero.add(jPanel1);
        jPanel1.setBounds(90, 150, 320, 30);

        btnCerrarCajero.setBackground(new java.awt.Color(255, 255, 204));
        btnCerrarCajero.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnCerrarCajero.setText("CERRAR EL CAJERO");
        btnCerrarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajeroActionPerformed(evt);
            }
        });
        pnlCajero.add(btnCerrarCajero);
        btnCerrarCajero.setBounds(0, 350, 520, 23);

        getContentPane().add(pnlCajero);
        pnlCajero.setBounds(135, 150, 520, 370);

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("ATRAS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(0, 650, 790, 23);

        lblFondoPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgAdmin/fondo1.jpg"))); // NOI18N
        lblFondoPng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblFondoPng);
        lblFondoPng.setBounds(0, 0, 790, 700);

        jMenu1.setText("Propiedades");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenu3.setText("Cambiar Fondo");
        jMenu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu3KeyPressed(evt);
            }
        });

        jMenuItem2.setText("Siguiente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Anterior");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Aleatorio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu2KeyPressed(evt);
            }
        });

        jMenuItem1.setText("Cajero");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator4);

        jMenu4.setText("Cuentas");

        jMenuItem5.setText("Añadir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Borrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem11.setText("Modificar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenu2.add(jMenu4);

        jMenuItem7.setText("Tarjetas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        fondo++;
        if (fondo == 11) {
            fondo = 1;
        }
        lblFondoPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgAdmin/fondo" + fondo + ".jpg")));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        fondo--;
        if (fondo == 0) {
            fondo = 10;
        }
        lblFondoPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgAdmin/fondo" + fondo + ".jpg")));
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        fondo = generaNumeroAleatorio();
        System.out.println(fondo);
        lblFondoPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgAdmin/fondo" + fondo + ".jpg")));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        pnlCajero.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAceptarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCajeroActionPerformed
        int dinero;
        try {
            dinero = Integer.parseInt(txfCajero.getText());

            if (rbCajeroIngresa.isSelected()) {
                IngresarDineroEnCajero(dinero, dineroEnCajero());
                lblCajeroRespuesta.setText("Total en cajero: " + dineroEnCajero() + ".00€");
            } else if (rbCajeroRetira.isSelected()) {
                RetirarDineroDelCajero(dinero, dineroEnCajero());
                lblCajeroRespuesta.setText("Total en cajero: " + dineroEnCajero() + ".00€");
            } else {
                lblCajeroRespuesta.setText("SELECCIONA UNA OPERACION");
            }
        } catch (Exception NumberFoException) {
            lblCajeroRespuesta.setText("Error! Introduce un valor correcto.");
        }

    }//GEN-LAST:event_btnAceptarCajeroActionPerformed

    private void txfCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCajeroActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jFAñadirCuenta.setVisible(true);
        this.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jFAñadirCuentaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFAñadirCuentaWindowClosed
        this.setFocusable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jFAñadirCuentaWindowClosed

    private void jFAñadirCuentaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFAñadirCuentaWindowClosing
        this.setEnabled(true);
    }//GEN-LAST:event_jFAñadirCuentaWindowClosing

    private void jFAñadirCuentaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFAñadirCuentaWindowOpened
        framePosicion(jFAñadirCuenta);
    }//GEN-LAST:event_jFAñadirCuentaWindowOpened

    private void jFAñadirCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFAñadirCuentaFocusGained
        framePosicion(jFAñadirCuenta);
    }//GEN-LAST:event_jFAñadirCuentaFocusGained

    private void btnCerrarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajeroActionPerformed
        pnlCajero.setVisible(false);
    }//GEN-LAST:event_btnCerrarCajeroActionPerformed

    private void btnCuentaAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaAñadirActionPerformed

        int longitudCuenta = txfCuentaAñadir.getText().length();
        if (longitudCuenta != 5) {
            lblCuentaAñadir.setText("Error! Longitud necesaria=5");
        } else {
            try {
                num_cuenta = Integer.parseInt(txfCuentaAñadir.getText());

                Statement sentenciaMovimiento = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                sentenciaMovimiento.executeUpdate("INSERT INTO cuenta(num_cuenta, saldo) values('" + num_cuenta + "','" + saldo + "')");
                lblCuentaAñadir.setText("Añadida");
            } catch (SQLException ex) {
                lblCuentaAñadir.setText("Existe una cuenta con este numero.");
            } catch (NumberFormatException ex) {
                lblCuentaAñadir.setText("Introduce numero de cuenta valido.");
            }
        }

    }//GEN-LAST:event_btnCuentaAñadirActionPerformed

    private void btnCuentaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaBorrarActionPerformed
        try {
            num_cuenta = Integer.parseInt(txfCuentaBorrar.getText());
            Statement sentenciaMovimiento = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sentenciaMovimiento.executeUpdate("DELETE FROM `cuenta` WHERE `cuenta`.`num_cuenta` ='" + num_cuenta + "'");
            lblCuentaBorrar.setText("Borrada");
        } catch (SQLException ex) {
            lblCuentaBorrar.setText(ex + "");
        } catch (NumberFormatException ex) {
            lblCuentaBorrar.setText("Introduce numero de cuenta valido.");
        }

    }//GEN-LAST:event_btnCuentaBorrarActionPerformed

    private void jFBorrarCuentaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFBorrarCuentaWindowClosed

    }//GEN-LAST:event_jFBorrarCuentaWindowClosed

    private void jFBorrarCuentaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFBorrarCuentaWindowClosing
        frameCerrar();        // TODO add your handling code here:
    }//GEN-LAST:event_jFBorrarCuentaWindowClosing

    private void jFBorrarCuentaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFBorrarCuentaWindowOpened
        framePosicion(jFBorrarCuenta);       // TODO add your handling code here:
    }//GEN-LAST:event_jFBorrarCuentaWindowOpened
    private boolean nuevoTitular = false;
    private void btnMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatosActionPerformed
        txfNombre.setText("");
        txfApes1.setText("");
        txfRespuestaModificarCuenta.setText("");
        if (txfCuentaModificar.getText().length() != 5) {
            txfRespuestaModificarCuenta.setText("Error, la longitud de la cuenta debe ser 5");
        } else {
            try {
                num_cuenta = Integer.parseInt(txfCuentaModificar.getText());

                sentencia = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String sql = "SELECT * FROM cuenta where num_cuenta='" + num_cuenta + "'";
                resultado = sentencia.executeQuery(sql);
                resultado.first();
            } catch (SQLException ex) {
                txfRespuestaModificarCuenta.setText("No existe");
            } catch (NumberFormatException e) {
                txfRespuestaModificarCuenta.setText("Error, la cuenta tiene que ser un numero de longitud 5");

            }

            try {
                num_cuenta = Integer.parseInt(txfCuentaModificar.getText());

                sentencia = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String sql = "SELECT * FROM usuario where id_cuenta='" + num_cuenta + "'";
                resultado = sentencia.executeQuery(sql);
                resultado.first();
                txfNombre.setText(resultado.getString("nombre"));
                txfApes1.setText(resultado.getString("Apellidos"));
            } catch (SQLException ex) {
                txfNombre.setText(">>>ANONIMO<<<");
                txfApes1.setText(">>>ANONIMO<<<");
                nuevoTitular = true;
            } catch (NumberFormatException e) {
                txfRespuestaModificarCuenta.setText("Error, la cuenta tiene que ser un numero de longitud 5");
            }
        }
    }//GEN-LAST:event_btnMostrarDatosActionPerformed

    private void jFModificarCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFModificarCuentaFocusGained

    }//GEN-LAST:event_jFModificarCuentaFocusGained

    private void jFModificarCuentaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFModificarCuentaWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFModificarCuentaWindowClosed

    private void jFModificarCuentaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFModificarCuentaWindowClosing
        frameCerrar();
    }//GEN-LAST:event_jFModificarCuentaWindowClosing

    private void jFModificarCuentaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFModificarCuentaWindowOpened
        framePosicion(jFModificarCuenta);        // TODO add your handling code here:
    }//GEN-LAST:event_jFModificarCuentaWindowOpened

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jFBorrarCuenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jFBorrarCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFBorrarCuentaFocusGained
        framePosicion(jFBorrarCuenta);  // TODO add your handling code here:
    }//GEN-LAST:event_jFBorrarCuentaFocusGained

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jFModificarCuenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (nuevoTitular == true) {

            Connection conexion = Conexion.mySQL("cajero", "root", "");
            if (conexion != null) {
                try { //Añadir filas a la table utilizando el objeto ResultSet 
                    resultado.moveToInsertRow();
                    String nombre = txfNombre.getText();
                    String apes = txfApes1.getText();
                    int cuenta = Integer.parseInt(txfCuentaModificar.getText());
                    Statement sentenciaMovimiento = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    sentenciaMovimiento.executeUpdate("INSERT INTO usuario(nombre, id_cuenta, Apellidos ) values('" + nombre + "','" + cuenta + "','" + apes + "')");
                    txfRespuestaModificarCuenta.setText("Operacion realizada con exito!");

                } catch (SQLException ex) {
                    txfRespuestaModificarCuenta.setText("Error! Asegurate de introducir bien los datos.");
                }

            }
        }
        nuevoTitular = false;
        try {
            num_cuenta = Integer.parseInt(txfCuentaModificar.getText());
            Statement sentenciaModificar = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "UPDATE `usuario` SET `nombre`='" + txfNombre.getText() + "',Apellidos='" + txfApes1.getText() + "' WHERE id_cuenta='" + num_cuenta + "'";
            PreparedStatement pst = conexion.prepareStatement(sql);
            pst.executeUpdate();
            txfRespuestaTarjeta.setText("Operacion realizada con exito!");
        } catch (SQLException ex) {
            txfRespuestaModificarCuenta.setText("Error, asegurate de introducir los datos correctamente.");
        } catch (NumberFormatException ex) {
            txfRespuestaModificarCuenta.setText("Error, asegurate de introducir 5 numeros en cuenta.");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void txfCuentaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCuentaModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCuentaModificarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        goTarjeta();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int longitudCuenta = txfCuentaTarjeta.getText().length();
        if (longitudCuenta != 5) {
            txfCuentaTarjeta.setText("Error! Longitud necesaria=5");
        } else {

            try {
                num_cuenta = Integer.parseInt(txfCuentaModificar.getText());

                sentencia = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                String sql = "SELECT * FROM cuenta where num_cuenta='" + num_cuenta + "'";
                resultado = sentencia.executeQuery(sql);
                resultado.first();
                resultado.getInt("num_cuenta");
            } catch (SQLException ex) {
                System.out.println(ex);
            } catch (NumberFormatException e) {
                txfRespuestaModificarCuenta.setText("Error, la cuenta tiene que ser un numero");
            }

            if (longitudCuenta != 4) {
                txfPinAñadir.setText("Error! Longitud necesaria=4");

            } else {
                int clave = Integer.parseInt(txfPinAñadir.getText());
                try {
                    Statement sentenciaMovimiento = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                    sentenciaMovimiento.executeUpdate("INSERT INTO tarjeta(id_cuenta, activa,id,clave) values('" + num_cuenta + "','" + 0 + "',null,'" + clave + "')");
                    System.out.println("Nuevo movimiento en la tabla movimientos.");
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfCuentaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCuentaTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCuentaTarjetaActionPerformed

    private void jMenu3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3KeyPressed

    private void jMenu2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2KeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setAlwaysOnTop(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.setAlwaysOnTop(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        goPrincipal();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCajero;
    private javax.swing.JButton btnCerrarCajero;
    private javax.swing.JButton btnCuentaAñadir;
    private javax.swing.JButton btnCuentaBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFAñadirCuenta;
    private javax.swing.JFrame jFBorrarCuenta;
    private javax.swing.JFrame jFModificarCuenta;
    private javax.swing.JFrame jFTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCajeroInfo;
    private javax.swing.JLabel lblCajeroRespuesta;
    private javax.swing.JLabel lblCuentaAñadir;
    private javax.swing.JLabel lblCuentaBorrar;
    private javax.swing.JLabel lblFondoPng;
    private javax.swing.JPanel pnlCajero;
    private javax.swing.JRadioButton rbCajeroIngresa;
    private javax.swing.JRadioButton rbCajeroRetira;
    public static javax.swing.ButtonGroup seleccionOperacionCajero;
    private javax.swing.JTextField txfApes1;
    private javax.swing.JTextField txfCajero;
    private javax.swing.JTextField txfCuentaAñadir;
    private javax.swing.JTextField txfCuentaBorrar;
    private javax.swing.JTextField txfCuentaModificar;
    private javax.swing.JTextField txfCuentaTarjeta;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPinAñadir;
    private javax.swing.JLabel txfRespuestaModificarCuenta;
    private javax.swing.JLabel txfRespuestaTarjeta;
    // End of variables declaration//GEN-END:variables
 //VARIABLES GLOBALES o DE CLASE:
    private Connection conexion;
    private Statement sentencia;
    private ResultSet resultado;
    private boolean datosModificados = false;
    private int tarjeta = 0;
    public Principal principal;
    private int pinCode;
    private int fondo = 1;
    private int dineroEnCajero;
    private int num_cuenta = 0;
    private int saldo = 0;

    //Ir a la ventana de inicio
    private void goPrincipal() {
        principal.setVisible(true);
        this.setVisible(false);
        principal.admin = "";
    }

    public static int generaNumeroAleatorio() {
        int num = (int) Math.floor(Math.random() * (10 - 1 + 1) + (1));
        return num;
    }

    private void cambiarPin() {
        Connection conexion = null;
        conexion = Conexion.mySQL("cajero", "root", "");
        if (conexion != null) {
            
//Paso 2: Ejecutar una consulta

            ResultSet rs = null;
            try {
                Statement sentencia = conexion.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                String sql = "UPDATE `cuenta` SET `clave`=" + pinCode + " WHERE num_cuenta='" + principal.cuentaValida + "'";
                PreparedStatement pst = conexion.prepareStatement(sql);
                int retorno = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Actualizado");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR" + e);
            }
        }

    }//metdo

    public int dineroEnCajero() {

        try {

            ResultSet rs = null;

            Statement sentencia = conexion.createStatement();

            String sql = "SELECT * FROM cajero";
            rs = sentencia.executeQuery(sql);
            rs.first();
            dineroEnCajero = rs.getInt("dinero");

            System.out.println(dineroEnCajero);
        } catch (SQLException ex) {
            System.out.println("Error");
        }

        return dineroEnCajero;
    }

    public void IngresarDineroEnCajero(int ingreso, int dineroEnCajero) {
        int total = ingreso + dineroEnCajero;

        if (conexion != null) {
            try {
                ResultSet rs = null;
                Statement sentencia = conexion.createStatement();
                String sql = "UPDATE `cajero` SET `dinero`='" + total + "'";
                PreparedStatement pst = conexion.prepareStatement(sql);
                int retorno = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, +ingreso + ".00€ ingresados en el cajero.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR" + e);
            }
        }
    }

    public void RetirarDineroDelCajero(int retiro, int dineroEnCajero) {
        if (retiro > dineroEnCajero) {
            JOptionPane.showMessageDialog(null, "El cajero no dispone con tanto dinero.");
        } else {
            int total = dineroEnCajero - retiro;

            if (conexion != null) {
                try {
                    ResultSet rs = null;
                    Statement sentencia = conexion.createStatement();
                    String sql = "UPDATE `cajero` SET `dinero`='" + total + "'";
                    PreparedStatement pst = conexion.prepareStatement(sql);
                    int retorno = pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, retiro + ".00 € retirados del cajero");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR" + e);
                }
            }
        }
    }

}
