/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import cajeroautomaticodian.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author bboyd
 */
public class PanelUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PanelUsuario(Principal principal) {
        initComponents();
        //initBaseDatos();
        ventanas();
        ocultarMenuPin();
        this.principal = principal;
        this.setTitle("Panel del usuario");
    }
    
    private void ocultarMenuPin() {
        lblPinCode.setVisible(false);
        lblPinViejo.setVisible(false);
        txfPinCode.setVisible(false);
        lblIntroducePin.setVisible(false);
        btnPin.setVisible(false);
    }
    
    private void visualizarMenuPin() {
        lblPinCode.setVisible(true);
        lblPinViejo.setVisible(true);
        txfPinCode.setVisible(true);
        lblIntroducePin.setVisible(true);
        btnPin.setVisible(true);
    }
    
    public void boton(java.awt.event.ActionEvent evt) {
        if (lblPinCode.isVisible()) { //si la tarjeta esta insertada
            JButton boton = (JButton) evt.getSource();
            txfPinCode.setText(txfPinCode.getText() + boton.getText());
        }
    }

    //* iniciar ventanas y botones 
    private void ventanas() {
        this.setSize(807, 740);//tamaño del jFrame
        this.setLocationRelativeTo(null); //jframe al centro
        lblTarjetaInsertada.setVisible(false); //este label se muestra cuando insertamos la tarjeta
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfPinCode = new javax.swing.JTextField();
        btnPin = new javax.swing.JButton();
        lblPinViejo = new javax.swing.JLabel();
        lblIntroducePin = new javax.swing.JLabel();
        lblPinCode = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        fasdf = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        lblTarjetaInsertada = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCmabiarPin = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        lblIngresarDinero = new javax.swing.JLabel();
        lblSacarDinero = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnSacarDinero = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnCambiaPin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVentana = new javax.swing.JLabel();
        lblFondoPng = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txfPinCode);
        txfPinCode.setBounds(170, 260, 190, 30);

        btnPin.setText("ACEPTAR");
        btnPin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinActionPerformed(evt);
            }
        });
        getContentPane().add(btnPin);
        btnPin.setBounds(170, 290, 190, 23);

        lblPinViejo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPinViejo.setText("TU CUENTA ES: ");
        getContentPane().add(lblPinViejo);
        lblPinViejo.setBounds(120, 120, 290, 50);

        lblIntroducePin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIntroducePin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntroducePin.setText("INTRODUCE EL NUEVO CODIGO");
        getContentPane().add(lblIntroducePin);
        lblIntroducePin.setBounds(170, 220, 190, 40);

        lblPinCode.setBackground(new java.awt.Color(255, 255, 204));
        lblPinCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPinCode.setOpaque(true);
        getContentPane().add(lblPinCode);
        lblPinCode.setBounds(90, 60, 350, 290);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 204));
        pnlBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        pnlBotones.setForeground(new java.awt.Color(255, 255, 204));
        pnlBotones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotones.setLayout(null);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn1);
        btn1.setBounds(40, 15, 52, 40);

        btn2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn2);
        btn2.setBounds(100, 15, 52, 40);

        btn3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn3);
        btn3.setBounds(160, 15, 52, 40);

        btn4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn4);
        btn4.setBounds(40, 60, 52, 40);

        fasdf.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pnlBotones.add(fasdf);
        fasdf.setBounds(240, 150, 100, 40);

        btn5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn5);
        btn5.setBounds(100, 60, 52, 40);

        btn6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn6);
        btn6.setBounds(160, 60, 52, 40);

        btn7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn7);
        btn7.setBounds(40, 105, 52, 40);

        btn8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn8);
        btn8.setBounds(100, 105, 52, 40);

        btn9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn9);
        btn9.setBounds(160, 105, 52, 40);

        jButton11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pnlBotones.add(jButton11);
        jButton11.setBounds(40, 150, 52, 40);

        btn0.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        pnlBotones.add(btn0);
        btn0.setBounds(100, 150, 52, 40);

        jButton13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pnlBotones.add(jButton13);
        jButton13.setBounds(160, 150, 52, 40);

        btnAceptar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAceptar);
        btnAceptar.setBounds(240, 15, 100, 40);

        btnBorrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnBorrar);
        btnBorrar.setBounds(240, 60, 100, 40);

        jButton17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        pnlBotones.add(jButton17);
        jButton17.setBounds(240, 105, 100, 40);

        getContentPane().add(pnlBotones);
        pnlBotones.setBounds(80, 380, 370, 210);

        lblTarjetaInsertada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPrincipal/tarjetaInsertada.png"))); // NOI18N
        lblTarjetaInsertada.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(lblTarjetaInsertada);
        lblTarjetaInsertada.setBounds(540, 320, 190, 30);

        lblConsultas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblConsultas.setText("<----CONSULTAS");
        getContentPane().add(lblConsultas);
        lblConsultas.setBounds(90, 120, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TRANSFERENCIA---->");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 220, 130, 20);

        lblCmabiarPin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCmabiarPin.setText("CAMBIAR PIN ---->");
        getContentPane().add(lblCmabiarPin);
        lblCmabiarPin.setBounds(330, 120, 110, 20);

        lblVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVolver.setText("<----VOLVER ATRAS");
        getContentPane().add(lblVolver);
        lblVolver.setBounds(90, 270, 140, 20);

        lblIngresarDinero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIngresarDinero.setText("<----INGRESAR DINERO");
        getContentPane().add(lblIngresarDinero);
        lblIngresarDinero.setBounds(90, 220, 160, 20);

        lblSacarDinero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSacarDinero.setText("<---- SACAR DINERO");
        getContentPane().add(lblSacarDinero);
        lblSacarDinero.setBounds(90, 170, 140, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("DONACION---->");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 270, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("MOVIMIENTOS---->");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 170, 110, 20);

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 260, 50, 40);

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 210, 50, 40);

        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultas);
        btnConsultas.setBounds(40, 110, 50, 40);

        btnSacarDinero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSacarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarDineroActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarDinero);
        btnSacarDinero.setBounds(40, 160, 50, 40);

        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(40, 260, 50, 40);

        btnCambiaPin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiaPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiaPinActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiaPin);
        btnCambiaPin.setBounds(440, 110, 50, 40);

        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(440, 160, 50, 40);

        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 210, 50, 40);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESIONE LA TECLA QUE DESEA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 60, 350, 30);

        lblVentana.setBackground(new java.awt.Color(255, 255, 204));
        lblVentana.setOpaque(true);
        getContentPane().add(lblVentana);
        lblVentana.setBounds(90, 60, 350, 290);

        lblFondoPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPrincipal/principal.jpg"))); // NOI18N
        lblFondoPng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblFondoPng);
        lblFondoPng.setBounds(0, 0, 790, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn1ActionPerformed
    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn2ActionPerformed
    
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn3ActionPerformed
    
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn4ActionPerformed
    
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn5ActionPerformed
    
    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn6ActionPerformed
    
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn7ActionPerformed
    
    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn8ActionPerformed
    
    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn9ActionPerformed
    
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        boton(evt);
    }//GEN-LAST:event_btn0ActionPerformed
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txfPinCode.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        goPrincipal();
        
    }//GEN-LAST:event_btnAtrasActionPerformed
    
    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        goConsultas();
    }//GEN-LAST:event_btnConsultasActionPerformed
    
    private void btnCambiaPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiaPinActionPerformed
        visualizarMenuPin();
        deshabilitarBotonesSuperiores();
        habilitarBotonesInferiores();
        lblPinViejo.setText("Cuenta: " + principal.cuentaValida);
    }//GEN-LAST:event_btnCambiaPinActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        goMovimientos();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void btnPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinActionPerformed
        int pinnuevo;
        if (txfPinCode.getText().length() == 4) {//comprobar longitud
            try {
                pinnuevo = Integer.parseInt(txfPinCode.getText());
                pinCode = pinnuevo;
                cambiarPin();
                ocultarMenuPin();
                habilitarBotonesSuperiores();
                deshabilitarBotonesInferiores();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(txfPinCode, "Error.");
            }
            
        } else {
            JOptionPane.showMessageDialog(txfPinCode, "Error, la longitud necesaria es 4.");
        }
        
    }//GEN-LAST:event_btnPinActionPerformed
    
    private void btnSacarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarDineroActionPerformed
        goRetiros();
    }//GEN-LAST:event_btnSacarDineroActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        goIngresos();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        goDonacion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        goTransferencia();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCambiaPin;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnPin;
    private javax.swing.JButton btnSacarDinero;
    private javax.swing.JButton fasdf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCmabiarPin;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblFondoPng;
    private javax.swing.JLabel lblIngresarDinero;
    private javax.swing.JLabel lblIntroducePin;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblPinViejo;
    private javax.swing.JLabel lblSacarDinero;
    private javax.swing.JLabel lblTarjetaInsertada;
    private javax.swing.JLabel lblVentana;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JTextField txfPinCode;
    // End of variables declaration//GEN-END:variables
 //VARIABLES GLOBALES o DE CLASE:
    private Connection conexion;
    private Statement sentencia;
    private ResultSet resultado;
    private boolean datosModificados = false;
    private int tarjeta = 0;
    public Principal principal;
    private int pinCode;
    private Movimientos movimientos = new Movimientos(this);
    private IngresarDinero ingresos = new IngresarDinero(this);
    private Consulta consultas = new Consulta(this);
    private SacarDinero retiros = new SacarDinero(this);
    private Donacion donacion = new Donacion(this);
    private Transferencia transferencia = new Transferencia(this);
    
    private void goTransferencia() {
        transferencia.setVisible(true);
        this.setVisible(false);
    }
    
    private void goDonacion() {
        donacion.setVisible(true);
        this.setVisible(false);
    }
    
    private void goPrincipal() {
        principal.setVisible(true);
        this.setVisible(false);
    }
    
    private void goMovimientos() {
        movimientos.setVisible(true);
        this.setVisible(false);
    }
    
    private void goIngresos() {
        ingresos.setVisible(true);
        this.setVisible(false);
    }
    
    private void goRetiros() {
        retiros.setVisible(true);
        this.setVisible(false);
    }
    
    private void goConsultas() {
        consultas.setVisible(true);
        this.setVisible(false);
    }
    
    private void cambiarPin() {
        Connection conexion = null;
        conexion = Conexion.mySQL("cajero", "root", "");
        if (conexion != null) {
            System.out.println("Conexion realizada con éxito");
//Paso 2: Ejecutar una consulta

            ResultSet rs = null;
            try {
                Statement sentencia = conexion.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(PanelUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                String sql = "UPDATE `tarjeta` SET `clave`=" + pinCode + " WHERE id_cuenta='" + principal.cuentaValida + "'";
                
                PreparedStatement pst = conexion.prepareStatement(sql);
                int retorno = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Actualizado");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR" + e);
            }
        }
        
    }//metdo

    private void deshabilitarBotonesSuperiores() {
        btnCambiaPin.setEnabled(false);
        jButton2.setEnabled(false);
        jButton7.setEnabled(false);
        jButton1.setEnabled(false);
        btnConsultas.setEnabled(false);
        btnSacarDinero.setEnabled(false);
        btnAtras.setEnabled(false);
        lblFondoPng.setEnabled(false);
    }
    
    private void habilitarBotonesSuperiores() {
        btnCambiaPin.setEnabled(true);
        jButton2.setEnabled(true);
        jButton7.setEnabled(true);
        jButton1.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnSacarDinero.setEnabled(true);
        btnAtras.setEnabled(true);
        lblFondoPng.setEnabled(true);
    }
    
    public void habilitarBotonesInferiores() {
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn0.setEnabled(true);
    }
    
    public void deshabilitarBotonesInferiores() {
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btn0.setEnabled(false);
    }
    
}
